// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv-CZeRHeyv63vsbW-WFNaWdLjMpNRbEw',
    appId: '1:369457486334:web:7d269e85dedde7087208af',
    messagingSenderId: '369457486334',
    projectId: 'sstaxi-71298',
    authDomain: 'sstaxi-71298.firebaseapp.com',
    storageBucket: 'sstaxi-71298.appspot.com',
    measurementId: 'G-9P61XZDD20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC76gaD0b0BzsKe7e5WfajStdy5ZF81go',
    appId: '1:369457486334:android:24e95148ac9d1f307208af',
    messagingSenderId: '369457486334',
    projectId: 'sstaxi-71298',
    storageBucket: 'sstaxi-71298.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmD-4vzCcDBu7xTE8fCLleqG0h0ESTo74',
    appId: '1:369457486334:ios:6567696df6835c147208af',
    messagingSenderId: '369457486334',
    projectId: 'sstaxi-71298',
    storageBucket: 'sstaxi-71298.appspot.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmD-4vzCcDBu7xTE8fCLleqG0h0ESTo74',
    appId: '1:369457486334:ios:ad3cf1833fe9c6697208af',
    messagingSenderId: '369457486334',
    projectId: 'sstaxi-71298',
    storageBucket: 'sstaxi-71298.appspot.com',
    iosBundleId: 'com.example.capstone.RunnerTests',
  );
}
